name: Restart Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  restart-space:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE_OWNER: byoung-hf
          HF_SPACE_NAME: ai-me
        run: |
          if [ -z "$HF_TOKEN" ]; then
            echo "HF_TOKEN is not set. Add it to repository secrets as HF_TOKEN." >&2
            exit 1
          fi

          API_URL="https://huggingface.co/api/spaces/${HF_SPACE_OWNER}/${HF_SPACE_NAME}/restart"

          echo "Calling Hugging Face Spaces restart API for ${HF_SPACE_OWNER}/${HF_SPACE_NAME}"
          echo "URL: $API_URL"

          # Run curl with verbose output to debug
          set +e  # Don't exit on curl error
          response=$(curl -v -w "\n%{http_code}" -X POST "$API_URL" -H "Authorization: Bearer $HF_TOKEN" 2>&1)
          curl_exit_code=$?
          set -e
          
          if [ $curl_exit_code -ne 0 ]; then
            echo "Curl failed with exit code: $curl_exit_code"
            echo "Full curl output:"
            echo "$response"
            exit 1
          fi
          
          http_status=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')

          echo "HTTP Status: $http_status"
          if [ -n "$body" ]; then
            echo "Response body: $body"
          fi

          if [ "$http_status" -ge 200 ] && [ "$http_status" -lt 300 ]; then
            echo "✓ Restart request accepted (HTTP $http_status)"
          else
            echo "✗ Failed to request restart (HTTP $http_status)" >&2
            exit 1
          fi
