name: Restart Hugging Face Space

on:
  push:
    branches:
      - main

jobs:
  restart-space:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE_OWNER: byoung-hf
          HF_SPACE_NAME: ben-bot
        run: |
          if [ -z "$HF_TOKEN" ]; then
            echo "HF_TOKEN is not set. Add it to repository secrets as HF_TOKEN." >&2
            exit 1
          fi

          API_URL="https://huggingface.co/api/spaces/${HF_SPACE_OWNER}/${HF_SPACE_NAME}/restart"

          echo "Restarting Hugging Face Space: ${HF_SPACE_OWNER}/${HF_SPACE_NAME}"

          http_status=$(curl -s -o /dev/null -w "%{http_code}" -X POST "$API_URL" -H "Authorization: Bearer $HF_TOKEN")

          if [ "$http_status" -ge 200 ] && [ "$http_status" -lt 300 ]; then
            echo "✓ Space restart successful (HTTP $http_status)"
          else
            echo "✗ Failed to restart Space (HTTP $http_status)" >&2
            exit 1
          fi
